SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, 
DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS A
    JOIN USED_GOODS_REPLY AS B ON A.BOARD_ID = B.BOARD_ID
WHERE YEAR(A.CREATED_DATE) = 2022 AND MONTH(A.CREATED_DATE) = 10
ORDER BY B.CREATED_DATE, A.TITLE


# YEAR의 경우 [ YEAR(날짜컬럼) = 값 ] 으로 해당 날짜 컬럼의 해당하는 연도 값만 반환 받을 수 있습니다.
# MONTH의 경우도 YEAR와 마찬가지로 [ MONTH(날짜컬럼) = 값 ] 으로 해당하는 월만 반환 받을 수 있습니다.